services:
  - type: web
    name: voice-agent-backend
    env: python
    buildCommand: pip install -r requirements-dev.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 8000
      - key: DATABASE_NAME
        fromDatabase:
          name: voice-agent-db
          property: name
      - key: MONGODB_URL
        fromDatabase:
          name: voice-agent-db
          property: connectionString

databases:
  - name: voice-agent-db
    databaseName: voice_agent
    user: voice_agent_user
