services:
  - type: web
    name: voice-agent-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: voice_agent
      - key: OPENAI_API_KEY
        sync: false
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production